-- ============================================
-- SCHEMA COMPLETO DO SISTEMA PDV - SUPABASE
-- ============================================

-- ============================================
-- TABELA DE CATEGORIAS
-- ============================================
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE FORNECEDORES
-- ============================================
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    cnpj VARCHAR(20) UNIQUE,
    email VARCHAR(100),
    phone VARCHAR(20),
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE PRODUTOS
-- ============================================
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(60) NOT NULL UNIQUE,
    description TEXT,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    cost_price NUMERIC(10,2) CHECK (cost_price >= 0),
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    min_stock INTEGER NOT NULL DEFAULT 0 CHECK (min_stock >= 0),
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE VENDAS
-- ============================================
CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC(12,2) NOT NULL CHECK (total >= 0),
    discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    payment_method VARCHAR(30),
    payment_status VARCHAR(20) NOT NULL DEFAULT 'completed',
    customer_name VARCHAR(150),
    customer_document VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'completed',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE ITENS DE VENDA
-- ============================================
CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    discount NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
    subtotal NUMERIC(12,2) NOT NULL CHECK (subtotal >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE MOVIMENTAÇÕES DE ESTOQUE
-- ============================================
CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('in', 'out', 'adjustment', 'return')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    reason TEXT,
    reference_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- TABELA DE USUÁRIOS (EXTENSÃO DO auth.users)
-- ============================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'employee',
    phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);
CREATE INDEX IF NOT EXISTS idx_products_low_stock ON products(quantity, min_stock) WHERE quantity <= min_stock;

CREATE INDEX IF NOT EXISTS idx_sales_created ON sales(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_payment ON sales(payment_method);

CREATE INDEX IF NOT EXISTS idx_sale_items_sale ON sale_items(sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product ON sale_items(product_id);

CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON stock_movements(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_created ON stock_movements(created_at DESC);

-- ============================================
-- TRIGGER PARA ATUALIZAR updated_at AUTOMATICAMENTE
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_suppliers_updated_at
    BEFORE UPDATE ON suppliers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_sales_updated_at
    BEFORE UPDATE ON sales
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================
-- TRIGGER PARA ATUALIZAR ESTOQUE AUTOMATICAMENTE
-- ============================================
CREATE OR REPLACE FUNCTION update_stock_on_sale()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE products
        SET quantity = quantity - NEW.quantity,
            updated_at = NOW()
        WHERE id = NEW.product_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE products
        SET quantity = quantity + OLD.quantity,
            updated_at = NOW()
        WHERE id = OLD.product_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER stock_update_on_sale
    AFTER INSERT OR DELETE ON sale_items
    FOR EACH ROW EXECUTE FUNCTION update_stock_on_sale();

-- ============================================
-- POLÍTICAS RLS (ROW LEVEL SECURITY)
-- ============================================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Política pública para categorias
CREATE POLICY "Anyone can read categories" ON categories
    FOR SELECT USING (true);

CREATE POLICY "Authenticated can manage categories" ON categories
    FOR ALL USING (auth.role() = 'authenticated');

-- Política pública para fornecedores
CREATE POLICY "Anyone can read suppliers" ON suppliers
    FOR SELECT USING (true);

CREATE POLICY "Authenticated can manage suppliers" ON suppliers
    FOR ALL USING (auth.role() = 'authenticated');

-- Política pública para produtos
CREATE POLICY "Anyone can read products" ON products
    FOR SELECT USING (active = true);

CREATE POLICY "Authenticated can manage products" ON products
    FOR ALL USING (auth.role() = 'authenticated');

-- Política para vendas
CREATE POLICY "Authenticated can manage sales" ON sales
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Anyone can read sales" ON sales
    FOR SELECT USING (true);

-- Política para itens de venda
CREATE POLICY "Authenticated can manage sale_items" ON sale_items
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Anyone can read sale_items" ON sale_items
    FOR SELECT USING (true);

-- Política para movimentações de estoque
CREATE POLICY "Anyone can read stock_movements" ON stock_movements
    FOR SELECT USING (true);

CREATE POLICY "Authenticated can manage stock_movements" ON stock_movements
    FOR ALL USING (auth.role() = 'authenticated');

-- Política para perfis
CREATE POLICY "Users can read own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Authenticated can manage profiles" ON profiles
    FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- INSERÇÕES INICIAIS (DADOS DE EXEMPLO)
-- ============================================

-- Categorias de exemplo
INSERT INTO categories (name, description) VALUES
    ('Bebidas', 'Bebidas em geral'),
    ('Alimentos', 'Alimentos e produtos alimentícios'),
    ('Cosméticos', 'Produtos de beleza e higiene'),
    ('Limpeza', 'Produtos de limpeza'),
    ('Outros', 'Outros produtos diversos')
ON CONFLICT (name) DO NOTHING;

-- Fornecedor de exemplo
INSERT INTO suppliers (name, cnpj, email, phone) VALUES
    ('Fornecedor Genérico LTDA', '12.345.678/0001-90', 'contato@fornecedor.com', '(11) 99999-9999')
ON CONFLICT (cnpj) DO NOTHING;

-- Produto de exemplo
INSERT INTO products (name, sku, price, cost_price, quantity, min_stock, category_id, supplier_id)
SELECT 'Produto Exemplo', 'EXEMP-001', 10.00, 5.00, 100, 10, c.id, s.id
FROM categories c, suppliers s
WHERE c.name = 'Outros' AND s.cnpj = '12.345.678/0001-90'
ON CONFLICT (sku) DO NOTHING;